name: test_firestore
description: Test del pacchetto cloud_firestore_custom da repo Git
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0  
  cloud_firestore_custom:
    git:
      url: https://github.com/damianotosi1973/cloud_firestore_custom.git
      ref: main
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
