
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

target 'Runner' do
  install_all_flutter_pods
end
